### PR TITLE
first change, open for a surprise

### PR DESCRIPTION
**Pull request by jolyssa**
OPEN UP!

### CODE REVIEW

**Review by QueenMissRose — APPROVED** [review]
approved. however i am slightly disappointed that the h1 you made doesn't have something more cute.

since i cruelfully spoiled the surprise for myself - i thought as you were changing it you were gunna make it super cute to make it *more* of a surprise. But alas, i was wrong.

nice site.

**Comment by QueenMissRose** [comment]
merge confirmed.

**Comment by jolyssa** [comment]
thx

**Comment by jolyssa** [comment]
👍🏾

**Comment by jolyssa** [comment]
i love u

**Comment by jolyssa** [comment]
...

**Comment by jolyssa** [comment]
shower teim or smoke teim

**Comment by QueenMissRose** [comment]
I love you too. I really hope this disappointing update will be taken into consideration for the next merge request.

**Comment by jolyssa** [comment]
considered!

**Comment by QueenMissRose** [comment]
excellent

**Comment by QueenMissRose** [comment]
with that out of the way, it's time to get back to work

**Comment by jolyssa** [comment]
answeer my questuon

**Comment by QueenMissRose** [comment]
Shower :)

**Comment by jolyssa** [comment]
ok

**Comment by jolyssa** [comment]
more snack?

**Comment by QueenMissRose** [comment]
wym more?

**Comment by jolyssa** [comment]
light mode ew

**Comment by QueenMissRose** [comment]
fuk yu

**Comment by jolyssa** [comment]
snak

**Comment by QueenMissRose** [comment]
i dont hate on dark mode dont hate on me

**Comment by jolyssa** [comment]
tru

**Comment by QueenMissRose** [comment]
where more snak we only bought one

**Comment by jolyssa** [comment]
cereal snak

**Comment by QueenMissRose** [comment]
oh no thats boring i had heaps during my zoomies

**Comment by jolyssa** [comment]
lol oki

**Comment by jolyssa** [comment]
i delete tthis fiirk now

**Comment by jolyssa** [comment]
fork

**Comment by jolyssa** [comment]
goodbye...

**Comment by QueenMissRose** [comment]
wait delete?

**Comment by jolyssa** [comment]
yes.... bye....

**Pull request merged**
